# golangci-lint configuration
# Minimal configuration compatible with current schema
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Error detection
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Style
    - revive
    - misspell
    - unconvert
    
    # Complexity
    - gocyclo
    - gocognit
    - nestif
    - funlen
    
    # Performance
    - prealloc
    - gocritic
    
    # Security
    - gosec
    
    # Best practices
    - goconst
    - dupl
    - lll
    - whitespace
    - asciicheck
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - forcetypeassert
    - goprintffuncname
    - makezero
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - wastedassign 